repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes, --line-length=79]
  - repo: https://github.com/ibm/detect-secrets
    rev: 0.13.1+ibm.62.dss
    hooks:
      - id: detect-secrets