services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: accessibility_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=accessibility_api.dev_settings
      - DB_HOST=db
      - DB_NAME=accessibility_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  caddy:
    image: caddy:2-alpine
    ports:
      - "8080:80"
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - ../accessRating.info_frontend:/app/frontend:ro
    depends_on:
      - web
    environment:
      - PUID=1000
      - PGID=1000

volumes:
  postgres_data:
