# Generated by Django 5.2.4 on 2025-07-07 18:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Business description')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(help_text='Full business address')),
                ('postcode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('what3words', models.CharField(blank=True, help_text='What3Words location', max_length=50)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('shop', 'Shop'), ('hotel', 'Hotel'), ('office', 'Office'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=20)),
                ('accessibility_rating', models.IntegerField(blank=True, choices=[(1, 'Limited Mobility Friendly'), (2, 'Wheelchair Accessible Entry'), (3, 'Accessible Bathroom'), (4, 'Changing Places Bathroom'), (5, 'Fully Accessible Events')], help_text='Official accessibility rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_assessed', models.DateTimeField(blank=True, null=True)),
                ('assessment_notes', models.TextField(blank=True, help_text='Internal assessment notes')),
                ('is_verified', models.BooleanField(default=False, help_text='Business ownership verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Business is active and accepting customers')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_businesses', to=settings.AUTH_USER_MODEL)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-created_at'],
            },
        ),
    ]
