# Generated by Django 5.2.4 on 2025-07-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="what3words",
        ),
        migrations.AlterField(
            model_name="business",
            name="latitude",
            field=models.DecimalField(
                decimal_places=9,
                default="51.507351",
                help_text="Latitude coordinate for Google Maps (required for map display)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="longitude",
            field=models.DecimalField(
                decimal_places=9,
                default="-0.127758",
                help_text="Longitude coordinate for Google Maps (required for map display)",
                max_digits=12,
            ),
        ),
    ]
